### ISSUE TITLE
no start/pauze buttons available anymore sincd v2.0.1

### ISSUE THREAD

**Issue by jodewee** [albaintor/homeassistant_electrolux_status#74]
since version 2.0.1

the start , pauze etc are no longer available since this version (remote start/pauze)

![image](https://github.com/user-attachments/assets/46190294-dce8-4863-a91a-1a57d502d1e0)

**Comment by jodewee** [comment]
[electrolux_status-29236c136be5034fade3a5aaa04a7a77-Afwasmachine-079e944eb566f8fd0a3c94cc1592a539.json](https://github.com/user-attachments/files/17382954/electrolux_status-29236c136be5034fade3a5aaa04a7a77-Afwasmachine-079e944eb566f8fd0a3c94cc1592a539.json)

**Comment by kingy444** [comment]
while you had them before, did these work previously ? from your json these are presented as an `access=read` which is why they arent created anymore
https://github.com/albaintor/homeassistant_electrolux_status/pull/61/files#diff-fcbf4040d636114b469be192e9fb07fe1e6bd16ae022ffc506c8a90a87b2a80aR234-R235

it doesnt look like v1 respected whether the api when it returned that `executeCommand`  was read/write or read only and just always created the entity

Not sure whether there is any ill effects to taking that same route in v2, but assume it is ok if your buttons used to work

https://github.com/albaintor/homeassistant_electrolux_status/pull/61/files#diff-fcbf4040d636114b469be192e9fb07fe1e6bd16ae022ffc506c8a90a87b2a80aL361-L407

```
          "executeCommand": {
            "access": "read",
            "type": "string",
            "values": {
              "PAUSE": {},
              "RESUME": {},
              "START": {},
              "STOPRESET": {}
            }
          },
          ```

**Comment by kingy444** [comment]
I'll also note that your device doesnt say it supports the `ON` and `OFF` commands at all - suspect that v1 was taking the inbuilt (hardcoded) definition and not the api version (again, probably not a good thing)

**Comment by jodewee** [comment]
it was available & worked till the upgrade:
![image](https://github.com/user-attachments/assets/f2cb0bee-d231-412c-9543-e1e17b54d219)

**Comment by jodewee** [comment]
Still no start or pauze buttons after the update 2.0.2

**Comment by jodewee** [comment]
[Uploading config_entry-electrolux_status-29236c136be5034fade3a5aaa04a7a77.json…]()

**Comment by jodewee** [comment]
@kingy444 ; manual update the 4 files you changed and i see the buttons again.
i'll check this evening or tomorrow if they also work effectively when i press them

**Comment by jodewee** [comment]
buttons are available again! Thanks!!
